FROM ubuntu:22.04@sha256:f9d633ff6640178c2d0525017174a688e2c1aef28f0a0130b26bd5554491f0da

ENV VERSION=22.04
ENV LC_CTYPE=C.UTF-8

WORKDIR /root

COPY setup.sh /
RUN /setup.sh

RUN mkdir -p /chal
WORKDIR /chal

ENTRYPOINT [ "/usr/bin/zsh" ]