FROM ubuntu:24.04@sha256:f8b860e4f9036f2694571770da292642eebcc4c2ea0c70a1a9244c2a1d436cd9

ENV VERSION=24.04
ENV LC_CTYPE=C.UTF-8

WORKDIR /root

COPY utils/ /usr/bin
COPY Templates/ /root/Templates

COPY setup.sh /
RUN /setup.sh

RUN mkdir -p /chal
WORKDIR /chal

ENTRYPOINT [ "/usr/bin/zsh" ]