FROM ubuntu:23.04@sha256:5a828e28de105c3d7821c4442f0f5d1c52dc16acf4999d5f31a3bc0f03f06edd

ENV VERSION=23.04
ENV LC_CTYPE=C.UTF-8

WORKDIR /root

COPY utils/ /usr/bin
COPY Templates /root/

COPY setup.sh /
RUN /setup.sh

RUN mkdir -p /chal
WORKDIR /chal

ENTRYPOINT [ "/usr/bin/zsh" ]