FROM ubuntu:25.04@sha256:9a302811bba2ae9533ddae0b563af29c112f1262329e508f13c0c532d5ba7c19

ENV VERSION=25.04
ENV LC_CTYPE=C.UTF-8

WORKDIR /root

COPY utils/ /usr/bin
COPY Templates/ /root/Templates

COPY setup.sh /
RUN /setup.sh

RUN mkdir -p /chal
WORKDIR /chal

ENTRYPOINT [ "/usr/bin/zsh" ]
