FROM ubuntu:20.04@sha256:c664f8f86ed5a386b0a340d981b8f81714e21a8b9c73f658c4bea56aa179d54a

ENV VERSION=20.04
ENV LC_CTYPE=C.UTF-8
ENV LANG en_us.utf8

WORKDIR /root

COPY utils/ /usr/bin
COPY Templates/ /root/Templates

COPY setup.sh /
RUN /setup.sh

RUN mkdir -p /chal
WORKDIR /chal

ENTRYPOINT [ "/usr/bin/zsh" ]
