FROM ubuntu:24.04@sha256:2e863c44b718727c860746568e1d54afd13b2fa71b160f5cd9058fc436217b30

ENV VERSION=24.04
ENV LC_CTYPE=C.UTF-8

WORKDIR /root

COPY utils/ /usr/bin
COPY Templates/ /root/Templates

COPY setup.sh /
RUN /setup.sh

RUN mkdir -p /chal
WORKDIR /chal

ENTRYPOINT [ "/usr/bin/zsh" ]