FROM ubuntu:18.04@sha256:152dc042452c496007f07ca9127571cb9c29697f42acbfad72324b2bb2e43c98

ENV VERSION=18.04
ENV LC_CTYPE=C.UTF-8
ENV LANG en_us.utf8

WORKDIR /root

COPY setup.sh /
RUN /setup.sh

RUN mkdir -p /chal
WORKDIR /chal

ENTRYPOINT [ "/usr/bin/zsh" ]
