FROM ubuntu:20.04@sha256:80ef4a44043dec4490506e6cc4289eeda2d106a70148b74b5ae91ee670e9c35d

ENV VERSION=20.04
ENV LC_CTYPE=C.UTF-8
ENV LANG en_us.utf8

WORKDIR /root

COPY utils/ /usr/bin
COPY Templates/ /root/Templates

COPY setup.sh /
RUN /setup.sh

RUN mkdir -p /chal
WORKDIR /chal

ENTRYPOINT [ "/usr/bin/zsh" ]
