FROM ubuntu:16.04@sha256:1f1a2d56de1d604801a9671f301190704c25d604a416f59e03c04f5c6ffee0d6

ENV VERSION=16.04
ENV LC_CTYPE=C.UTF-8

WORKDIR /root

COPY setup.sh /
RUN /setup.sh

RUN mkdir -p /chal
WORKDIR /chal

ENTRYPOINT [ "/usr/bin/zsh" ]