#!/bin/bash

function usage() {
	echo "Usage: $0 <version>"
	echo "Available versions:"
	for i in "${AVAILABLE[@]}"; do
		echo -en "\t $i"
		[ "$i" == "$DEFAULT" ] && echo -n "   <-- Default"
		echo
	done
	echo; exit 1
}

IMAGE="theflash2k/pwn-dev"
DEFAULT="latest"
AVAILABLE=("latest" "2304" "2204" "2004" "1804" "1604")

TAG=""
if [[ $# -ne 1 ]]; then
	TAG="$DEFAULT"
else
	if [[ "$1" == "-h" || "$1" == "--help" ]]; then
		usage
	else
		for i in "${AVAILABLE[@]}"; do
			if [[ "$1" == "$i" || "$i" == "$1""04" ]]; then
				TAG="$i"
				break
			fi
		done
	fi
fi
[ -z "$TAG" ] && TAG="$DEFAULT"

echo "[*] Running $IMAGE version: $TAG"

docker run \
	-it \
	--rm \
	--name "pwn-dev-$TAG" \
	--hostname "pwn-dev-$TAG" \
	--device=/dev/kvm \
	--network host \
	--ipc=host \
	--cap-add sys_ptrace \
	--security-opt seccomp=unconfined \
	--env "DISPLAY=$DISPLAY" \
	--env "_X11_NO_MITSHM=1" \
	-v /tmp/.X11-unix:/tmp.X11-unix \
	-v `pwd`:/chal \
	--privileged \
	"$IMAGE:$TAG"
