FROM theflash2k/pwn-chal:latest

# Just install the 32-bit stuff
RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y libc6:i386 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
